# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine as builder

WORKDIR /app

# Copy package files and install full dependencies including dev dependencies for building
COPY package*.json ./
RUN npm install

# Copy all source files and build the project
COPY . .
RUN npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy only necessary files for production
COPY package*.json ./
RUN npm install --production

# Copy build output from builder stage
COPY --from=builder /app/build ./build

CMD ["node", "build/index.js"]
